name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.20', '1.21.x' , '1.23' ]

    steps:
    - uses: actions/checkout@v3

    - name: Run tests
      run: make gotest

    - name: Run build
      run: make gobuild
