name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.x' ]

    steps:
    - uses: actions/checkout@v3
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: install gomigrate.
      run: |
           curl -L https://packagecloud.io/golang-migrate/migrate/gpgkey | apt-key add -
           echo "deb https://packagecloud.io/golang-migrate/migrate/ubuntu/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/migrate.list
           apt-get update
           apt-get install -y migrate
           
    - name: setup postgres
      uses: ikalnytskyi/action-setup-postgres@v4
      with:
        username: root
        password: secret
        database: simple_bank
        port: 5432
      id: postgres
        
    - name: initdb tables
      run: make migrateup
      
    - name: Run tests
      run: make gotest

    - name: Run build
      run: make gobuild
